
//###############################################################
//														        #
//	This code was generated by a PowerFunctionsReportDSL tool.	#
//	Changes to this file may cause incorrect behavior	        #
//	and will be lost if the code is regenerated.		        #
//														        #
//###############################################################


using System;
using System.Collections.Generic;
using System.Linq;
using TelventDMS.Common.DMS.Common;
using System.Runtime.Serialization;


namespace TelventDMS.Services.JobManagerService.EMSLoadFlowReport
{
	/// <summary>
	/// Class containing the result for <see cref="DataGrid1Record">.
	/// </summary>
    [DataContract]
    public partial class DataGrid1Results : EMSLoadFlowReportResult
    {
        #region Constructors

		/// <summary>
		/// Default constructor
		/// </summary>
		public DataGrid1Results()
		{
			EMSLoadFlowReportType = EMSLoadFlowReportType.Tab1;
		}
      

        #endregion Constructors

        #region Properties

		/// <summary>
		/// The collection containing DataGrid1 records <see cref="DataGrid1Record"/>
		/// </summary>
		[DataMember]
		public List<DataGrid1Record> Records { get; set; }


        #endregion Properties
    }
}
