
//###############################################################
//														        #
//	This code was generated by a PowerFunctionsReportDSL tool.	#
//	Changes to this file may cause incorrect behavior	        #
//	and will be lost if the code is regenerated.		        #
//														        #
//###############################################################

using System;
using System.Collections.Generic;
using System.Linq;
using TelventDMS.Common.DMS.Common;
using System.Runtime.Serialization;


namespace TelventDMS.Services.JobManagerService.EMSLoadFlowReport
{
	/// <summary>
	/// Results for nodes
	/// </summary>
    [DataContract]
    public partial class EMSLoadFlowNodeRecord : HierarchicalReportRecord
    {
        #region Constructors

		/// <summary>
		/// Default constructor
		/// </summary>
		public EMSLoadFlowNodeRecord()
		{
		}
        

        #endregion Constructors

        #region Properties
        
		/// <summary>
		/// Voltage of node
		/// </summary>
		[DataMember]
		public ELimitViolation Voltage { get; set; }

		[DataMember]
		public float VoltageLevel { get; set; }

		[DataMember]
		public float PNode { get; set; }




        #endregion Properties
    }
}
