
//###############################################################
//														        #
//	This code was generated by a PowerFunctionsReportDSL tool.	#
//	Changes to this file may cause incorrect behavior	        #
//	and will be lost if the code is regenerated.		        #
//														        #
//###############################################################


using System;
using System.Collections.Generic;
using System.Linq;
using TelventDMS.Common.DMS.Common;
using System.Runtime.Serialization;


namespace TelventDMS.Services.JobManagerService.EMSLoadFlowReport
{
    [DataContract]
    public partial class EMSLoadFlowSwitchingDeviceResults : EMSLoadFlowReportResult
    {
        #region Constructors

		public EMSLoadFlowSwitchingDeviceResults()
		{
			ReportType = EMSLoadFlowReportType.EMSLoadFlowSwitchingDevice;
		}
      

        #endregion Constructors

        #region Properties

		[DataMember]
		public List<EMSLoadFlowSwitchingDeviceRecord> EMSLoadFlowSwitchingDeviceRecords { get; set; }


        #endregion Properties
    }
}
