
//###############################################################
//														        #
//	This code was generated by a PowerFunctionsReportDSL tool.	#
//	Changes to this file may cause incorrect behavior	        #
//	and will be lost if the code is regenerated.		        #
//														        #
//###############################################################

using System.Collections.Generic;
using System.Runtime.Serialization;


namespace TelventDMS.Services.JobManagerService.EMSLoadFlowReport
{

	[DataContract]
    public partial class EMSLoadFlowReportJobParam: JobParam
    {
        #region Properties

		[DataMember]
		public List<long> SelectedRecords { get; set; }
		[DataMember]
		public HierarchyType HierarchyType { get; set; }
		[DataMember]
		public EMSLoadFlowReportType ReportType { get; set; }
		[DataMember]
		public HierarchyNetworkType HierarchyNetworkType { get; set; }


        #endregion Properties

    }
}
