
//###############################################################
//														        #
//	This code was generated by a PowerFunctionsReportDSL tool.	#
//	Changes to this file may cause incorrect behavior	        #
//	and will be lost if the code is regenerated.		        #
//														        #
//###############################################################

namespace TelventDMS.Services.JobManagerService.EMSLoadFlowReport
{
    public enum EMSLoadFlowReportType
    {

		Node,
		Section,
		NoResults,


    }
}