//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchneiderElectricDMS.PowerFunctionsReportDSL
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "ui";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"PowerFunctionsReportDSL";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"SchneiderElectricDMS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID PowerFunctionsReportDSLDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PowerFunctionsReportDSLCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID PowerFunctionsReportDSLExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PowerFunctionsReportDSLCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewPowerFunctionsReportDSLExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PowerFunctionsReportDSLCommandSetId), 0x0001);
	
		// Package identifier
		public const string PowerFunctionsReportDSLPackageId = "70351ecb-93e9-4b2a-b34c-8f45a72a8e37";
		
		// Editor factory identifier
		public const string PowerFunctionsReportDSLEditorFactoryId = "7d7406f9-ee01-4a77-804a-bf591476ce84";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string PowerFunctionsReportDSLModelExplorerToolWindowId = "18de1779-9172-4a19-b541-326f320c5a4f";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace SchneiderElectricDMS.PowerFunctionsReportDSL
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string PowerFunctionsReportDSLCommandSetId = "47472abb-4a9b-4e8e-b893-a865ca4245f6";
	}
}