//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchneiderElectricDMS.PowerFunctionsReportDSL
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "ui";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"PowerFunctionsReportDSL";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"SchneiderElectricDMS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID PowerFunctionsReportDSLDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PowerFunctionsReportDSLCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID PowerFunctionsReportDSLExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PowerFunctionsReportDSLCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewPowerFunctionsReportDSLExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(PowerFunctionsReportDSLCommandSetId), 0x0001);
	
		// Package identifier
		public const string PowerFunctionsReportDSLPackageId = "36189604-6446-4d2c-be43-fbb6d87ba77e";
		
		// Editor factory identifier
		public const string PowerFunctionsReportDSLEditorFactoryId = "0f86ccf2-8107-445a-97dc-c2958521b825";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string PowerFunctionsReportDSLModelExplorerToolWindowId = "5c7fe4a1-755c-40cd-8227-ff738d5914d6";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace SchneiderElectricDMS.PowerFunctionsReportDSL
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string PowerFunctionsReportDSLCommandSetId = "a0febddb-b15a-4140-89b8-755953df8dc3";
	}
}