
//###############################################################
//														        #
//	This code was generated by a PowerFunctionsReportDSL tool.	#
//	Changes to this file may cause incorrect behavior	        #
//	and will be lost if the code is regenerated.		        #
//														        #
//###############################################################


using System.Runtime.Serialization;
using TelventDMS.Common.DMS.Common;


namespace TelventDMS.Services.JobManagerService.EMSLoadFlowReport.EMSLoadFlowReport
{
    [DataContract]
    [KnownType(typeof(EMSLoadFlowCapacitorReportResult))]

    public class EMSLoadFlowReport : JobResult
    {
        #region Constructors

         public EMSLoadFlowReport()
		{
		}
      

        #endregion Constructors

        #region Properties

        

        public EMSLoadFlowReportType EMSLFReportType { get; set; }

		

        #endregion Properties
    }
}
