
//###############################################################
//														        #
//	This code was generated by a PowerFunctionsReportDSL tool.	#
//	Changes to this file may cause incorrect behavior	        #
//	and will be lost if the code is regenerated.		        #
//														        #
//###############################################################

using System.Runtime.Serialization;
using TelventDMS.Common.DMS.Common;

 
namespace TelventDMS.Services.JobManagerService.EMSLoadFlowReport.EMSLoadFlowCapacitorReportRecord
{
    [DataContract]
    public class EMSLoadFlowCapacitorReportRecord
    {

        #region Constructors

        public EMSLoadFlowCapacitorReportRecord()
        {
        }        

        #endregion Constructors

        #region Properties


        #endregion Properties
    }
}
